name: Backend & Frontend Test

on:
  push:
    branches: [ "production", "main", "development" ]
  pull_request:
    branches: [ "production", "main", "development" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      mysql:
        # Docker Hub image (also with version)
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE:  db_test_laravel
        ## map the "external" 33306 port with the "internal" 3306
        ports:
          - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:

    - uses: "shivammathur/setup-php@v2"
      with:
        php-version: '8.3'
    - uses: "actions/checkout@v3"

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # - name: Install Dependencies
    #   run: composer update

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # - name: Create Database
    #   run: |
    #     mkdir -p database
    #     touch database/database.sqlite

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install Node Dependencies
      run: npm ci

    # - name: Install Dependencies
    #   run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Copy Environment File
      run: cp .env.example .env

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Publish Ziggy Configuration
      run: php artisan ziggy:generate

    - name: Build Assets
      run: npm run build

    - name: Run Code Formatting
      run: ./vendor/bin/pint

    - name: Run Code Static Analysis
      run: ./vendor/bin/phpstan analyse --memory-limit=2G
      
    - name: Execute tests (Unit and Feature tests) via Pest
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: db_test_laravel
        DB_PORT: 33306
        DB_USER: root
      run: php artisan test --parallel


